(ns de.levering-it.dom-mock.impl.protocols.document
  (:refer-clojure :exclude [remove]))


(defprotocol Document
  ;; Methods
  #_(adopt-node [this node])
  #_(append [this elements])
  #_(caret-position-from-point [this x y])
  #_(clear [this])
  #_(close [this])
  (create-attribute [this name])
  (create-attribute-ns [this namespace-uri qualified-name])
  #_(create-cdata-section [this data])
  (create-comment [this data])
  #_(create-document-fragment [this])
  (create-element [this tag-name])
  (create-element-ns [this namespace-uri qualified-name])
  #_(create-event [this event-interface])
  #_(create-expression [this expression resolver])
  #_(create-node-iterator [this root what-to-show filter])
  #_(create-ns-resolver [this node-resolver])
  #_(create-processing-instruction [this target data])
  #_(create-range [this])
  (create-text-node [this data])
  #_(create-tree-walker [this root what-to-show filter])
  #_(element-from-point [this x y])
  #_(elements-from-point [this x y])
  #_(evaluate [this expression context-node resolver type result])
  #_(exec-command [this command-id show-ui value-arg])
  #_(exit-fullscreen [this])
  #_(exit-picture-in-picture [this])
  #_(exit-pointer-lock [this])
  #_(get-animations [this])
  #_(get-element-by-id [this element-id])
  #_(get-elements-by-class-name [this class-names])
  #_(get-elements-by-name [this name])
  #_(get-elements-by-tag-name [this tag-name])
  #_(get-elements-by-tag-name-ns [this namespace-uri local-name])
  #_(has-focus [this])
  #_(import-node [this node deep])
  #_(open [this url name features replace])
  #_(prepend [this elements])
  #_(query-command-enabled [this command-id])
  #_(query-command-indeterm [this command-id])
  #_(query-command-state [this command-id])
  #_(query-command-supported [this command-id])
  #_(query-command-value [this command-id])
  #_(query-selector [this selectors])
  #_(query-selector-all [this selectors])
  #_(release-events [this])
  #_(write [this text])
  #_(writeln [this text])
  (get-active-element [this])
  #_(get-adopted-style-sheets [this])
  #_(get-alink-color [this])
  #_(get-all [this])
  #_(get-anchors [this])
  #_(get-applets [this])
  #_(get-bg-color [this])
  #_(get-body [this])
  #_(get-character-set [this])
  #_(get-child-element-count [this])
  #_(get-children [this])
  #_(get-compat-mode [this])
  #_(get-content-type [this])
  #_(get-cookie [this])
  #_(get-current-script [this])
  #_(get-default-view [this])
  #_(get-design-mode [this])
  #_(get-dir [this])
  #_(get-doctype [this])
  #_(get-document-element [this])
  #_(get-document-uri [this])
  #_(get-domain [this])
  #_(get-embeds [this])
  #_(get-feature-policy [this])
  #_(get-fg-color [this])
  #_(get-first-element-child [this])
  #_(get-fonts [this])
  #_(get-forms [this])
  #_(get-fragment-directive [this])
  #_(get-fullscreen [this])
  #_(get-fullscreen-element [this])
  #_(get-fullscreen-enabled [this])
  #_(get-head [this])
  #_(get-hidden [this])
  #_(get-images [this])
  #_(get-implementation [this])
  #_(get-last-element-child [this])
  #_(get-last-modified [this])
  #_(get-last-style-sheet-set [this])
  #_(get-link-color [this])
  #_(get-links [this])
  #_(get-location [this])
  #_(get-picture-in-picture-element [this])
  #_(get-picture-in-picture-enabled [this])
  #_(get-plugins [this])
  #_(get-pointer-lock-element [this])
  #_(get-preferred-style-sheet-set [this])
  #_(get-prerendering [this])
  #_(get-ready-state [this])
  #_(get-referrer [this])
  #_(get-root-element [this])
  #_(get-scripts [this])
  #_(get-scrolling-element [this])
  #_(get-selected-style-sheet-set [this])
  #_(get-style-sheets [this])
  #_(get-style-sheet-sets [this])
  #_(get-timeline [this])
  #_(get-title [this])
  #_(get-url [this])
  #_(get-visibility-state [this])
  #_(get-vlink-color [this])
  #_(get-xml-encoding [this])
  #_(get-xml-version [this]))